### ISSUE TITLE
Can't resolve all parameters for ScrollbarHelper errror in ngx-datatable with Angular v8.0.0-rc.0 and above

### ISSUE THREAD

**Issue by neetu-pandey** [swimlane/ngx-datatable#1693]
**I'm submitting a ...**  (check one with "x")
```
[ x] bug report => search github for a similar issue or PR before submitting
[ ] feature request[ ] support request => Please do not submit support request here, post on Stackoverflow or Gitter
```

**Current behavior**
Cannot launch ngx-datatable v14.0.0 with Angular v8.0.0-rc4.
Get the following error:

ERROR Error: Uncaught (in promise): Error: Can't resolve all parameters for ScrollbarHelper: (?).
Error: Can't resolve all parameters for ScrollbarHelper: (?).

**Expected behavior**
ngx-datatable should render without the error

**Reproduction of the problem**
https://stackblitz.com/edit/angular8-ngx-datatable

**What is the motivation / use case for changing the behavior?**
ScrollbarHelper class imports DOCUMENT from @angular/platform-browser. This deprecated import has been removed from Angular in v8.0.0-rc.0.
DOCUMENT should rather be imported from @angular/core.
https://github.com/angular/angular/issues/28117

**Please tell us about your environment:**
Windows 10, VSC, npm

* **Table version:** 
14.0.0

* **Angular version:** 
~8.0.0-rc4 (reproducible since ~8.0.0-rc.0)

* **Browser:** 
All

* **Language:** All

**Comment by bleuscyther** [comment]
i think its in ```@angular/common```

**Comment by bleuscyther** [comment]
There is a pull request on angular 8: 
https://github.com/swimlane/ngx-datatable/pull/1690

` npm rm @swimlane/ngx-datatable`
` npm install git+https://github.com/zackarychapple/ngx-datatable.git`

It seems  to work fine for now with **_ng serve_**

**Comment by pedromarce** [comment]
is there an estimated date when the pull request might be merged?

**Comment by marjan-georgiev** [comment]
Released 15.0.0. Please verify.

**Comment by neetu-pandey** [comment]
This issue is fixed. Thanks.

**Comment by sridharsivichandran** [comment]
umable to access this URL

**Comment by daniloff200** [comment]
LOL
@zackarychapple, I also can't do it :D :D

**Comment by daniloff200** [comment]
@sridharsivichandran  you can use latest version of ngx-datable, like 16.0.2
if you face some issue with icons path, check the https://github.com/swimlane/ngx-datatable/issues/1741

**Comment by zackarychapple** [comment]
Sorry for removing that repo, did not know folks were relying on it.  Thank you @daniloff200 for clarifying that the fix has been merged.

**Comment by jacques-hoventer** [comment]
I still get this error even after uninstalling v 14.x and installing 16.x. I have no idea how to troubleshoot any further than I have.

**Comment by pradosh123** [comment]
@jacques-hoventer im having same issue..you got any solution

**Comment by pradosh123** [comment]
> I still get this error even after uninstalling v 14.x and installing 16.x. I have no idea how to troubleshoot any further than I have.
> 
> PS. The ngx-datatable is used in a lazy loaded module, not sure if this makes any difference.
> 
> I'm on Angular 8.2.13.

 iam having same issue..you got any solution?

**Comment by jacques-hoventer** [comment]
I can't actually remember how I resolved this. I've since moved on to a different project, but if it comes back to me, I'll come back to you. Apologies.

**Comment by Ahmed-Diab** [comment]
i have the same issue any one got solution ?

**Comment by daniel-van-niekerk** [comment]
Same issue. Angular 11.0 and ngx-datatable 19.0.0.

The table works in a normal component but not in a mat dialog.

**Comment by notenote087** [comment]
> Same issue. Angular 11.0 and ngx-datatable 19.0.0.
> 
> The table works in a normal component but not in a mat dialog.

Same issue :(

**Comment by Predhin** [comment]
Same issue!

**Comment by fincha** [comment]
No solution for datatable in modals yet?
