### ISSUE TITLE
Reordering columns throws an exception and no further operation can be performed on the grid

### ISSUE THREAD

**Issue by emonney** [swimlane/ngx-datatable#438]
**I'm submitting a ...**  (check one with "x")
```
[x] bug report => search github for a similar issue or PR before submitting
[ ] feature request
[ ] support request => Please do not submit support request here
```

**Current behavior**

Immediately after a column is reordered, the exception "_./DataTableHeaderComponent class DataTableHeaderComponent - inline template:7:8 caused by: object unsubscribed_" is thrown and no further operation (such as column reordering, sorting) can be performed on the grid

**Expected behavior**

Sorting, reordering, all feature set should continue to work

**Reproduction of the problem**

Go to the [demo application](http://swimlane.github.io/ngx-datatable) (happens in local version too) and drag and reorder any column. After reordering no further sorting or re ordering can be done

**What is the motivation / use case for changing the behavior?**

The grid should not stop working after a standard operation. It only works again until the entire page is reloaded

**Please tell us about your environment:**

* **Table version:** 5.0.0

* **Angular version:** 2.4.3

* **Browser:** [chrome | firefox | MS Edge]

**Comment by emonney** [comment]
@amcdnl  Issue doesn't seem to be related to reordering only. Sorting also randomly throws the same exception: _"./DataTableHeaderComponent class DataTableHeaderComponent - inline template:7:8 caused by: object unsubscribed"_  and brings the entire application down.

**Comment by amcdnl** [comment]
Can you make a demo?

**Comment by emonney** [comment]
The online demo here: [http://swimlane.github.io/ngx-datatable/](http://swimlane.github.io/ngx-datatable).
Try to reorder the columns. It only works the first time (Then throws error => Check console for error). After that everything else stops working.

**Comment by amcdnl** [comment]
Fixed :)

**Comment by emonney** [comment]
:D

**Comment by emonney** [comment]
Resolved. Thnx!

**Comment by rotemx** [comment]
I'm still having an issue when removing a column and them restoring it, and then doing it again, and on the second time i'm restoring it I'm getting an "object unsubscribed" error. 
I'm using version 6.0.2 with angular 2.4.5.
any ideas ?
thanks

**Comment by guslep** [comment]
@rotemx I have the same problem as you
Easy step to reproduce 
In the demo app -> column-toggle.ts
replace this.columns = [...this.columns, col];
by this.columns = this.allColumns;

Once the app is loaded try to toggle the Name Coulmn, the first untoggle/toggle works
but if you try to re untoggle/toggle than it breaks

**Comment by amcdnl** [comment]
I think this has been resolved. I'm about to do a new build and can you retest?
