### ISSUE TITLE
Repository fails to build following instructions

### ISSUE THREAD

**Issue by achimha** [swimlane/ngx-datatable#465]
**I'm submitting a ...**  (check one with "x")
```
[X] bug report => search github for a similar issue or PR before submitting
[ ] feature request
[ ] support request => Please do not submit support request here
```

**Current behavior**
Trying to build the repository, I run into a problem with webpack:

```
> @swimlane/ngx-datatable@6.0.0 start /Users/achimha/Downloads/ngx-datatable
> webpack-dev-server

Invalid configuration object. Webpack has been initialised using a configuration object that does not match the API schema.
 - configuration.module.rules[2].loaders should be one of these:
   non-empty string | function | object { loader?, options?, query? } | function | [non-empty string | function | object { loader?, options?, query? }]
   Details:
```

Is this because you're expecting a certain version of webpack? Opening this as a bug because I believe a git clone followed by npm init should work on a pristine system.

**Expected behavior**

**Reproduction of the problem**
```
git clone https://github.com/swimlane/ngx-datatable
cd ngx-datatable
npm init
npm start
```

**Please tell us about your environment:**
OS X 10.12
NPM fetches webpack 2.2.0 and webpack-dev-server 2.2.0.

* **Table version:** 0.7.x
6.0.0

* **Angular version:** 2.0.x
2.4.5

* **Browser:** [all | Chrome XX | Firefox XX | IE XX | Safari XX | Mobile Chrome XX | Android X.X Web Browser | iOS XX Safari | iOS XX UIWebView | iOS XX WKWebView ]
all
* **Language:** [all | TypeScript X.X | ES6/7 | ES5]

**Comment by Alex-Tsyganok** [comment]
I faced same error today.

**Comment by amcdnl** [comment]
Fixed.

**Comment by achimha** [comment]
Sorry to turn this into a support ticket. With the latest code the text extract plugin doesn't cause the failure but it still fails to build, with the scss files. I suppose the webpack rules are not correct there.

```
ERROR in ./src/themes/material.scss
Module build failed: Error
    at /foo/ngx-datatable/node_modules/webpack/lib/NormalModule.js:141:35

```

The error occurs for all scss files.

**Comment by amcdnl** [comment]
delete all the node_modules and reinstall.

**Comment by achimha** [comment]
True, thank you!
