### ISSUE TITLE
tolocalestring undefined

### ISSUE THREAD

**Issue by sureshhustle** [swimlane/ngx-datatable#535]
hi i had problem when include [footerHeight]="50", it shows that error
**EXCEPTION: Uncaught (in promise): Error: Error in ./DataTableFooterComponent class DataTableFooterComponent - inline template:7:15 caused by: Cannot read property 'toLocaleString' of undefined
Error: Error in ./DataTableFooterComponent class DataTableFooterComponent - inline template:7:15 caused by: Cannot read property 'toLocaleString' of undefined**  

Please anyone help to solve this issue

**Comment by amcdnl** [comment]
Fixed in latest.

**Comment by Zyzle** [comment]
I'm not sure this has been completely resolved, I'm still seeing the issue when the rows are provided via an `@Input()` property and the angular `async` pipe for example

```html
<my-component [items]="items$ | async"></my-component>
```
where my-component is:
```typescript
@Component({
  // ...
  template: `
    <ngx-datatable class="material" [rows]="items" [columns]="columns"
    [columnMode]="'force'"
    [rowHeight]="'auto'"
    [footerHeight]="50"></ngx-datatable>
`
})
export class MyComponent implements OnInit {
  @Input()
  items: item[];

 // ...
}

**Comment by jarodsmk** [comment]
@amcdnl I'm receiving a similar issue to this:

ERROR Error: Uncaught (in promise): TypeError: Cannot read property 'toLocaleString' of undefined
TypeError: Cannot read property 'toLocaleString' of undefined
    at Object.eval [as updateRenderer] (DataTableFooterComponent.html:20)

Seems to point to the line:
`{{rowCount.toLocaleString()}} {{totalMessage}}`

Please advise? Using the latest release :)

**Comment by michalzfania** [comment]
still happens in latest. @1.7.1

**Comment by iget-master** [comment]
@amcdnl 

It's not fixed. It's happening here when I use footerHeight and define pagination values (using external pagination).

**Comment by OraCool** [comment]
I have solved this problem for myself initializing rowCount in the component's constructor:
![image](https://user-images.githubusercontent.com/127194/34234684-a31340e6-e5fd-11e7-819a-80dcc826938b.png)
![image](https://user-images.githubusercontent.com/127194/34234694-aa96437c-e5fd-11e7-99bd-8761becf8c97.png)

**Comment by miloskovacevic** [comment]
@OraCool  thank you my man!

**Comment by hilame** [comment]
@miloskovacevic  can you copy your code and how you do it

**Comment by miloskovacevic** [comment]
@hilame yup , here 
![table_html](https://user-images.githubusercontent.com/10956715/39708884-a96a473c-5218-11e8-999a-a77ad1a9e161.png)

![table_ts](https://user-images.githubusercontent.com/10956715/39708893-b11ed1a0-5218-11e8-9f99-7098e276b051.png)
