### ISSUE TITLE
Failed to load datatable.component.css

### ISSUE THREAD

**Issue by sh977218** [swimlane/ngx-datatable#730]
I'm experiencing an error in chrome:
`GET http://localhost:3001/datatable.component.css 404 (Not Found)`
`Unhandled Promise rejection: Failed to load datatable.component.css ; Zone: <root> ; Task: Promise.then ; Value: Failed to load datatable.component.css undefined`

I'm using:
angular 2.4.10
ngx-datatable: 6.3.0

This post says it's been fixed: [https://github.com/swimlane/ngx-datatable/issues/459](url)
Is anyone else still having the same issue?

**Comment by amcdnl** [comment]
This is fixed in latest.

**Comment by jrhite** [comment]
@amcdnl did this problem return?

I'm seeing the same error and I have version 9.3.0.

**Comment by sh977218** [comment]
I believe this issue has been fixed in the latest release.

**Comment by texasaggie96** [comment]
I am still experiencing the same issue with the following setup:

angular ->  4.2.3
angular-cli -> 1.1.1
ngx-datatable -> 9.3.0

The **_only_** way I could get this to work is to replace line 886 of 
[datatable.component.js](https://github.com/swimlane/ngx-datatable/blob/master/release/components/datatable.component.js) with:

`styleUrls: [require('./datatable.component.css')],`
